version: '3.1'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:  
      - postgresdb
    image: app
    hostname: app
    ports:
      - "8081:8081"
    depends_on:
      - postgresdb
    networks:
      - my-network

  postgresdb:
    image: postgres
    container_name: "postgresdb"
    hostname: postgresdb-host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=bookswhislist
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
networks:
  my-network:
volumes:  
  postgresql:
  postgresql_data: